language: csharp  
sudo: required  
mono: none
dotnet: 3.1.402
dist: xenial
node_js:
  - "14.2"
before_install:
- openssl aes-256-cbc -K $encrypted_d479270c765b_key -iv $encrypted_d479270c765b_iv
  -in myServerKey.enc -out myServerKey -d
- eval "$(ssh-agent -s)"
- chmod 600 myServerKey
- ssh-add myServerKey
install:
  - npm install ./news-client
scripts:
  - dotnet restore ./news-server/news-server.sln
  - dotnet build ./news-server/news-server.sln
  - npm build ./news-client
addons:
  ssh_known_hosts: 165.227.158.125  
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh
  on:
    branch: master
