language: csharp  
sudo: required  
mono: none
dotnet: 3.1.402
dist: xenial
scripts:
  - dotnet restore ./news-server/news-server.sln
  - dotnet build ./news-server/news-server.sln

language: node_js
node_js:
  - "14.2"
install:
  - npm install ./news-client
scripts:
  - npm build ./news-client