language: csharp  
sudo: required  
mono: none
dotnet: 3.1.402
dist: xenial
node_js:
  - "14.2"
before_deploy:
- openssl aes-256-cbc -K $encrypted_d479270c765b_key -iv $encrypted_d479270c765b_iv
  -in myServerKey.enc -out myServerKey -d
- ssh-keyscan -H $server >> ~/.ssh/known_hosts
- eval "$(ssh-agent -s)"
- chmod 600 myServerKey
- ssh-keygen -p -P $pass -N "" -f myServerKey
- ssh-add myServerKey
- ssh -i myServerKey root@$server pwd
install:
  - npm install ./news-client
scripts:
  - dotnet restore ./news-server/news-server.sln
  - dotnet build ./news-server/news-server.sln
  - npm build ./news-client
addons:
  ssh_known_hosts: $server
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
