language: csharp  
sudo: required  
mono: none
dotnet: 3.1.402
dist: xenial
node_js:
  - "14.2"
after_success:
   - openssl aes-256-cbc -K $encrypted_d7becb892f62_key -iv $encrypted_d7becb892f62_iv
   -in myServerKey.enc -out $TRAVIS_BUILD_DIR/myServerKey -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./myServerKey
  - ssh-add ./myServerKey
  - ssh -i ./myServerKey root@$IP pwd
install:
  - npm install ./news-client  
scripts:
  - dotnet restore ./news-server/news-server.sln
  - dotnet build ./news-server/news-server.sln
  - npm build ./news-client
addons:
  ssh_known_hosts: 165.227.158.125  
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh
  on:
    branch: master
