language: csharp  
sudo: required  
mono: none
dotnet: 3.1.402
dist: xenial
node_js:
  - "14.2"
before_deploy:
- eval "$(ssh-agent -s)"
- ssh-add $keyS
- ssh -i $keyS root@$server pwd
install:
  - npm install ./news-client
scripts:
  - dotnet restore ./news-server/news-server.sln
  - dotnet build ./news-server/news-server.sln
  - npm build ./news-client
addons:
  ssh_known_hosts: $server
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh
  on:
    branch: master
