language: csharp  
sudo: required  
mono: none
dotnet: 3.1.402
dist: xenial
node_js:
  - "14.2"
install:
  - npm install ./news-client
scripts:
  - dotnet restore ./news-server/news-server.sln
  - dotnet build ./news-server/news-server.sln
  - npm build ./news-client



